export const FURNITURE_CATEGORIES = Object.freeze({
  TABLE: 'TABLE',
  CHAIR: 'CHAIR',
  BED: 'BED',
  SOFA: 'SOFA',
  STORAGE: 'STORAGE',
  APPLIANCE: 'APPLIANCE',
  LIGHTING: 'LIGHTING',
  RUG: 'RUG',
  SPECIAL: 'SPECIAL',
  OTHER: 'OTHER',
})

export const FURNITURE_ARCHETYPES = Object.freeze({
  DESK: 'DESK',
  DINING_TABLE: 'DINING_TABLE',
  COFFEE_TABLE: 'COFFEE_TABLE',
  ROUND_COFFEE_TABLE: 'ROUND_COFFEE_TABLE',
  OFFICE_CHAIR: 'OFFICE_CHAIR',
  DINING_CHAIR: 'DINING_CHAIR',
  STOOL: 'STOOL',
  SINGLE_BED: 'SINGLE_BED',
  DOUBLE_BED: 'DOUBLE_BED',
  TWO_SEAT_SOFA: 'TWO_SEAT_SOFA',
  THREE_SEAT_SOFA: 'THREE_SEAT_SOFA',
  WARDROBE: 'WARDROBE',
  BOOKSHELF: 'BOOKSHELF',
  CABINET: 'CABINET',
  NIGHTSTAND: 'NIGHTSTAND',
  DESK_PEDESTAL: 'DESK_PEDESTAL',
  CHEST_OF_DRAWERS: 'CHEST_OF_DRAWERS',
  OPEN_BOOKSHELF: 'OPEN_BOOKSHELF',
  GARMENT_RACK: 'GARMENT_RACK',
  REFRIGERATOR: 'REFRIGERATOR',
  WASHING_MACHINE: 'WASHING_MACHINE',
  FLOOR_LAMP: 'FLOOR_LAMP',
  DESK_LAMP: 'DESK_LAMP',
  TABLE_LAMP: 'TABLE_LAMP',
  AREA_RUG: 'AREA_RUG',
  LADDER_SPECIAL: 'LADDER_SPECIAL',
  OTHER: 'OTHER',
})

export const FURNITURE_TAXONOMY_V0 = Object.freeze({
  [FURNITURE_CATEGORIES.TABLE]: Object.freeze([
    FURNITURE_ARCHETYPES.DESK,
    FURNITURE_ARCHETYPES.DINING_TABLE,
    FURNITURE_ARCHETYPES.COFFEE_TABLE,
    FURNITURE_ARCHETYPES.ROUND_COFFEE_TABLE,
  ]),
  [FURNITURE_CATEGORIES.CHAIR]: Object.freeze([
    FURNITURE_ARCHETYPES.OFFICE_CHAIR,
    FURNITURE_ARCHETYPES.DINING_CHAIR,
    FURNITURE_ARCHETYPES.STOOL,
  ]),
  [FURNITURE_CATEGORIES.BED]: Object.freeze([
    FURNITURE_ARCHETYPES.SINGLE_BED,
    FURNITURE_ARCHETYPES.DOUBLE_BED,
  ]),
  [FURNITURE_CATEGORIES.SOFA]: Object.freeze([
    FURNITURE_ARCHETYPES.TWO_SEAT_SOFA,
    FURNITURE_ARCHETYPES.THREE_SEAT_SOFA,
  ]),
  [FURNITURE_CATEGORIES.STORAGE]: Object.freeze([
    FURNITURE_ARCHETYPES.WARDROBE,
    FURNITURE_ARCHETYPES.BOOKSHELF,
    FURNITURE_ARCHETYPES.CABINET,
    FURNITURE_ARCHETYPES.NIGHTSTAND,
    FURNITURE_ARCHETYPES.DESK_PEDESTAL,
    FURNITURE_ARCHETYPES.CHEST_OF_DRAWERS,
    FURNITURE_ARCHETYPES.OPEN_BOOKSHELF,
    FURNITURE_ARCHETYPES.GARMENT_RACK,
  ]),
  [FURNITURE_CATEGORIES.APPLIANCE]: Object.freeze([
    FURNITURE_ARCHETYPES.REFRIGERATOR,
    FURNITURE_ARCHETYPES.WASHING_MACHINE,
  ]),
  [FURNITURE_CATEGORIES.LIGHTING]: Object.freeze([
    FURNITURE_ARCHETYPES.FLOOR_LAMP,
    FURNITURE_ARCHETYPES.DESK_LAMP,
    FURNITURE_ARCHETYPES.TABLE_LAMP,
  ]),
  [FURNITURE_CATEGORIES.RUG]: Object.freeze([
    FURNITURE_ARCHETYPES.AREA_RUG,
  ]),
  [FURNITURE_CATEGORIES.SPECIAL]: Object.freeze([
    FURNITURE_ARCHETYPES.LADDER_SPECIAL,
  ]),
  [FURNITURE_CATEGORIES.OTHER]: Object.freeze([
    FURNITURE_ARCHETYPES.OTHER,
  ]),
})

export const ARCHETYPE_TO_CATEGORY = Object.freeze(
  Object.fromEntries(
    Object.entries(FURNITURE_TAXONOMY_V0).flatMap(([category, archetypes]) => (
      archetypes.map((archetype) => [archetype, category])
    )),
  ),
)

export function isKnownFurnitureArchetype(value) {
  return Object.prototype.hasOwnProperty.call(ARCHETYPE_TO_CATEGORY, value)
}

export function categoryForArchetype(archetype) {
  return ARCHETYPE_TO_CATEGORY[archetype] ?? FURNITURE_CATEGORIES.OTHER
}
