import { normalizeFurnitureSemantic } from './furnitureSemantic.js'
import { FURNITURE_ARCHETYPES } from './furnitureTaxonomy.js'

export const MODEL_STRATEGIES = Object.freeze({
  PARAMETRIC: 'PARAMETRIC',
  LIBRARY: 'LIBRARY',
  GENERATED: 'GENERATED',
})

export const MODEL_STRATEGY_BY_ARCHETYPE = Object.freeze({
  [FURNITURE_ARCHETYPES.DOUBLE_BED]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.DESK]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.ROUND_COFFEE_TABLE]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.NIGHTSTAND]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.DESK_PEDESTAL]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.CHEST_OF_DRAWERS]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.OPEN_BOOKSHELF]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.GARMENT_RACK]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.AREA_RUG]: MODEL_STRATEGIES.PARAMETRIC,
  [FURNITURE_ARCHETYPES.OFFICE_CHAIR]: MODEL_STRATEGIES.LIBRARY,
  [FURNITURE_ARCHETYPES.TWO_SEAT_SOFA]: MODEL_STRATEGIES.LIBRARY,
  [FURNITURE_ARCHETYPES.FLOOR_LAMP]: MODEL_STRATEGIES.LIBRARY,
  [FURNITURE_ARCHETYPES.DESK_LAMP]: MODEL_STRATEGIES.LIBRARY,
  [FURNITURE_ARCHETYPES.TABLE_LAMP]: MODEL_STRATEGIES.LIBRARY,
  [FURNITURE_ARCHETYPES.LADDER_SPECIAL]: MODEL_STRATEGIES.GENERATED,
})

export const FURNITURE_MODEL_ROUTER_V0 = MODEL_STRATEGY_BY_ARCHETYPE

export function routeFurnitureModelStrategy(semanticInput) {
  const semantic = normalizeFurnitureSemantic(semanticInput)
  return MODEL_STRATEGY_BY_ARCHETYPE[semantic.archetype] ?? null
}

export function createModelStrategy(semanticInput, resolved = null) {
  return {
    preferred: routeFurnitureModelStrategy(semanticInput),
    resolved,
  }
}
