import assert from 'node:assert/strict'
import test from 'node:test'
import { createEvidence } from '../src/decision/common/evidence.js'
import { applyMovePreferenceWeighting } from '../src/decision/preferences/movePreferenceWeighting.js'
import { applyPurchasePreferenceWeighting } from '../src/decision/preferences/purchasePreferenceWeighting.js'

const purchaseEvidence = (ruleId, signal) => createEvidence({ ruleId, domain: 'PURCHASE', category: 'UTILITY', signal, reason: 'fixture', evidencePaths: ['fixture'] })
const moveEvidence = (ruleId, signal, category = 'UTILITY') => createEvidence({ ruleId, domain: 'MOVE', category, signal, reason: 'fixture', evidencePaths: ['fixture'] })

test('MEDIUM defaults are neutral and produce no modifiers', () => { const result = applyPurchasePreferenceWeighting({ evidence: [purchaseEvidence('P_SR04_REPEATED_FRICTION', 'SUPPORTS_BUY')] }); assert.deepEqual(result.modifiers, []); assert.ok(result.diagnostics.unusedProfileDimensions.includes('budgetCaution')) })
test('Friction sensitivity modifies only existing friction evidence', () => { const evidence = [purchaseEvidence('P_SR04_REPEATED_FRICTION', 'SUPPORTS_BUY')]; assert.equal(applyPurchasePreferenceWeighting({ evidence, userProfile: { frictionSensitivity: 'HIGH' } }).modifiers[0].effect, 'AMPLIFY'); assert.equal(applyPurchasePreferenceWeighting({ evidence, userProfile: { frictionSensitivity: 'LOW' } }).modifiers[0].effect, 'DAMPEN'); assert.deepEqual(applyPurchasePreferenceWeighting({ evidence: [], userProfile: { frictionSensitivity: 'HIGH' } }).modifiers, []) })
test('Favorite and aestheticWeight remain separate', () => { const evidence = [purchaseEvidence('P_SR08_FAVORITE_VALUE', 'SUPPORTS_BUY')]; assert.equal(applyPurchasePreferenceWeighting({ evidence, userProfile: { aestheticWeight: 'HIGH' } }).modifiers[0].effect, 'AMPLIFY'); assert.equal(applyPurchasePreferenceWeighting({ evidence, userProfile: { aestheticWeight: 'LOW' } }).modifiers[0].effect, 'DAMPEN'); assert.deepEqual(applyPurchasePreferenceWeighting({ evidence: [], userProfile: { aestheticWeight: 'HIGH' } }).modifiers, []) })
test('Substitute and wait preferences follow direction without scores', () => { const evidence = [purchaseEvidence('P_SR03_ADEQUATE_SUBSTITUTE', 'AGAINST_BUY'), purchaseEvidence('P_SR09_HIGH_UNCERTAINTY', 'SUPPORTS_WAIT')]; const result = applyPurchasePreferenceWeighting({ evidence, userProfile: { multifunctionPreference: 'HIGH', uncertaintyTolerance: 'LOW', immediacyPreference: 'HIGH' } }); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'multifunctionPreference').effect, 'AMPLIFY'); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'uncertaintyTolerance').effect, 'AMPLIFY'); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'immediacyPreference').effect, 'DAMPEN') })
test('Move logistics, long-term and favorite preferences modify existing evidence', () => { const evidence = [moveEvidence('M_SR04_LOW_USAGE_HIGH_BURDEN', 'AGAINST_TAKE', 'LOGISTICS'), moveEvidence('M_SR11_HIGH_FUTURE_REUSE', 'SUPPORTS_TAKE', 'LIFECYCLE'), moveEvidence('M_SR10_FAVORITE_VALUE', 'SUPPORTS_TAKE', 'PREFERENCE')]; const result = applyMovePreferenceWeighting({ evidence, userProfile: { moveLightnessPreference: 'HIGH', longTermOwnershipPreference: 'HIGH', aestheticWeight: 'HIGH' } }); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'moveLightnessPreference').effect, 'AMPLIFY'); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'longTermOwnershipPreference').effect, 'AMPLIFY'); assert.equal(result.modifiers.find(({ profileKey }) => profileKey === 'aestheticWeight').effect, 'AMPLIFY') })
test('Sentimental evidence is not dampened by ordinary profiles', () => { const result = applyMovePreferenceWeighting({ evidence: [moveEvidence('M_SR06_SENTIMENTAL_VALUE', 'SUPPORTS_TAKE', 'PREFERENCE')], userProfile: { aestheticWeight: 'LOW', moveLightnessPreference: 'HIGH' } }); assert.deepEqual(result.modifiers, []) })
test('Original Evidence is not mutated and invalid profile values normalize to MEDIUM', () => { const evidence = [purchaseEvidence('P_SR08_FAVORITE_VALUE', 'SUPPORTS_BUY')]; const before = structuredClone(evidence); const result = applyPurchasePreferenceWeighting({ evidence, userProfile: { aestheticWeight: 'INVALID' } }); assert.deepEqual(evidence, before); assert.deepEqual(result.modifiers, []); assert.deepEqual(result.evidence, before) })
test('Hard rule results are outside preference weighting', () => { const result = applyPurchasePreferenceWeighting({ evidence: [], userProfile: { spaceSensitivity: 'LOW' } }); assert.deepEqual(result.modifiers, []) })
